// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zshgbvphnaihwzmabuia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzaGdidnBobmFpaHd6bWFidWlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTIyMzUsImV4cCI6MjA2OTk4ODIzNX0.b_b3Rsmh2Hu3R6uBmEVp2JpahujwBcOnDkC0luT-47E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});